{"tests": 11, "errors": 1, "results": [{"skipped_msg": null, "error_trace": null, "test_method_name": "test_spike_api_pass_3", "failure_trace": null, "test_class_name": "SpikeAPITests", "result": "PASSED"}, {"skipped_msg": null, "error_trace": null, "test_method_name": "test_spike_api_pass_1", "failure_trace": null, "test_class_name": "SpikeAPITests", "result": "PASSED"}, {"skipped_msg": null, "error_trace": null, "test_method_name": "test_spike_api_pass_2", "failure_trace": null, "test_class_name": "SpikeAPITests", "result": "PASSED"}, {"skipped_msg": null, "error_trace": null, "test_method_name": "test_spike_api_fail", "failure_trace": "Traceback (most recent call last):\n  File \"/Users/jaydeepc/PycharmProjects/opencafe_spike/spikeroast/spikeroast/spikeroast/test_spike_api.py\", line 20, in test_spike_api_fail\n    self.assertEquals(1, 2, msg = \"This is false\")\nAssertionError: This is false\n", "test_class_name": "SpikeAPITests", "result": "FAILED"}, {"skipped_msg": null, "error_trace": null, "test_method_name": "test_spike_api_fail_2", "failure_trace": "Traceback (most recent call last):\n  File \"/Users/jaydeepc/PycharmProjects/opencafe_spike/spikeroast/spikeroast/spikeroast/test_spike_api.py\", line 24, in test_spike_api_fail_2\n    self.assertEquals(1, 2, msg = \"This is false again\")\nAssertionError: This is false again\n", "test_class_name": "SpikeAPITests", "result": "FAILED"}, {"skipped_msg": null, "error_trace": null, "test_method_name": "test_spike_api_fail_3", "failure_trace": "Traceback (most recent call last):\n  File \"/Users/jaydeepc/PycharmProjects/opencafe_spike/spikeroast/spikeroast/spikeroast/test_spike_api.py\", line 28, in test_spike_api_fail_3\n    self.assertEquals(1, 2, msg = \"This is false again\")\nAssertionError: This is false again\n", "test_class_name": "SpikeAPITests", "result": "FAILED"}, {"skipped_msg": null, "error_trace": null, "test_method_name": "test_spike_api_fail_4", "failure_trace": "Traceback (most recent call last):\n  File \"/Users/jaydeepc/PycharmProjects/opencafe_spike/spikeroast/spikeroast/spikeroast/test_spike_api.py\", line 32, in test_spike_api_fail_4\n    self.assertEquals(1, 2, msg = \"This is false again\")\nAssertionError: This is false again\n", "test_class_name": "SpikeAPITests", "result": "FAILED"}, {"skipped_msg": null, "error_trace": null, "test_method_name": "test_spike_api_fail_5", "failure_trace": "Traceback (most recent call last):\n  File \"/Users/jaydeepc/PycharmProjects/opencafe_spike/spikeroast/spikeroast/spikeroast/test_spike_api.py\", line 36, in test_spike_api_fail_5\n    self.assertEquals(1, 2, msg = \"This is false again\")\nAssertionError: This is false again\n", "test_class_name": "SpikeAPITests", "result": "FAILED"}, {"skipped_msg": null, "error_trace": null, "test_method_name": "test_spike_api_fail_6", "failure_trace": "Traceback (most recent call last):\n  File \"/Users/jaydeepc/PycharmProjects/opencafe_spike/spikeroast/spikeroast/spikeroast/test_spike_api.py\", line 40, in test_spike_api_fail_6\n    self.assertEquals(1, 2, msg = \"This is false again\")\nAssertionError: This is false again\n", "test_class_name": "SpikeAPITests", "result": "FAILED"}, {"skipped_msg": null, "error_trace": "Traceback (most recent call last):\n  File \"/Users/jaydeepc/PycharmProjects/opencafe_spike/spikeroast/spikeroast/spikeroast/test_spike_api.py\", line 49, in test_spike_api_error\n    a.error\nAttributeError: 'Response' object has no attribute 'error'\n", "test_method_name": "test_spike_api_error", "failure_trace": null, "test_class_name": "SpikeAPITests", "result": "ERROR"}, {"skipped_msg": "Just like that", "error_trace": null, "test_method_name": "test_spike_api_skip", "failure_trace": null, "test_class_name": "SpikeAPITests", "result": "SKIPPED"}], "skips": 1, "time": "11.8627870083", "failures": 6}